### ISSUE TITLE
Crash bug when a song is removed from a user playlist

### ISSUE THREAD

**Issue by adam-codersgu** [adam-codersgu/supernova#117]

**Comment by adam-codersgu** [comment]
Example log
```
2024-03-03 22:54:17.343 32766-32766 AndroidRuntime          com.codersguidebook.supernova        E  FATAL EXCEPTION: main
                                                                                                    Process: com.codersguidebook.supernova, PID: 32766
                                                                                                    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolderSongWithHandle{87e10ad position=11 id=-1, oldPos=11, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{38cc746 VFED..... ......I. 0,0-1096,1987 #7f090222 app:id/recyclerView}, adapter:com.codersguidebook.supernova.fragment.adapter.PlaylistAdapter@1d07b4c, layout:androidx.recyclerview.widget.LinearLayoutManager@dcc5d07, context:com.codersguidebook.supernova.MainActivity@b347c81
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6590)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6796)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
                                                                                                    	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
                                                                                                    	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2381)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2024-03-03 22:54:17.344 32766-32766 AndroidRuntime          com.codersguidebook.supernova        E  	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at com.android.internal.policy.DecorView.onLayout(DecorView.java:815)
                                                                                                    	at android.view.View.layout(View.java:23157)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6412)
                                                                                                    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3693)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3152)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2138)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8686)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:859)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:346)
                                                                                                    	at android.os.Looper.loop(Looper.java:475)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7889)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
2024-03-03 22:54:17.365 32766-32766 Process                 com.codersguidebook.supernova        I  Sending signal. PID: 32766 SIG: 9
---------------------------- PROCESS ENDED (32766) for package com.codersguidebook.supernova ----------------------------
```

**Comment by adam-codersgu** [comment]
Working on branch bug/song_removal_crash

**Comment by adam-codersgu** [comment]
Merged and fixed https://github.com/adam-codersgu/supernova/pull/125
